services:
  hedera-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "com.example.description=Hedera App Demo"
      - "com.example.version=1.0.0"